---
name: Ejercitación - Layout
locale: es
type: learning
beta: false
teacher_info: ''
language: html
id_format: "%05d"
order:
- 2
- 3
- 8
- 7
- 11
- 9
- 10
- 5
- 4
- 6
- 1
- 12
- 13
- 14
- 15
private: false
